# Generated by Django 6.0.6 on 2026-06-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taom', '0002_dish_slug_restaurant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
